### PR TITLE
Add proposal for one year anniversary

### PR DESCRIPTION
**Pull request by pxlpnk**

### CODE REVIEW

**Comment by febeling** [comment]
Lgtm. :100:

**Comment by plexus** [comment]
Dankuwel!

**Comment by til** [comment]
@pxlpnk thanks for writing this, awesome!

(and I just realized I had neither watched nor starred this repo, well Duh!)

**Comment by pxlpnk** [comment]
What is now missing is an announcement on the mailing list and some tweets and loads and loads of sharing! (:

**Comment by plexus** [comment]
I just mentioned on the mailing list that there's an announcement up on the site. Or where you thinking of something more elaborate?

I can do some tweeting as well. What's really missing is some lightning talk topics ;)

**Pull request merged**
