### PR TITLE
Jitsi self hosted

### PR DESCRIPTION
**Pull request by til**
This is a minimal start for a self-hosted Jitsi instance, on a single AWS EC2 instance. The instance size could be increased before the meetup, to what size exactly I'd like to research still.

@Ebert-Hanke I've tried to copy the essential parts from the config you shared, except for limiting the creation of new rooms to authenticated users, this still needs to be done. Please let me know if you see anything else missing.

### CODE REVIEW

**Comment by til** [comment]
In case anyone wonders, I didn't bother putting the full installation into ansible. For jitsi packages installation and letsencrypt setup I performed the steps described in https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart manually. It might make sense to add that later, but for now a functioning server is good enough.

**Comment by til** [comment]
I'd try to use an `m5n.2xlarge` instance during the meetup: 8 vCPU, 32GB RAM, and up to 25Gbps traffic. Costs less than one :beer: to run it for a few hours.

**Comment by Ebert-Hanke** [comment]
Config looks good to me. Great work with all the automation in terraform / ansible! Thats really cool! 👏 I was using a 4 vcore 8 gig instance with Hetzner running at 0,023€/h and we never maxed the CPU so far. The AWS instance should be more than powerful enough I guess. I read different things about the allowed udp ports, some mention a range `10000:20000/udp`. Not sure if this makes a big difference.

**Comment by til** [comment]
Great, thanks for checking. I'll open that udp port range as well just to be sure, it can't do any harm.

**Comment by Ebert-Hanke** [comment]
If you havent already done that, we can also quickly test if the instance works.

**Pull request merged**
